// "use client"

import axios from "axios";
import Link from "next/link";
import React from "react";
import "./user.css";
import { DELETE, GET } from "../../api/users/route";
import { deleteUser } from "../../_lib/server-action";
// import userModel from "../../_lib/model/user";
import { revalidatePath } from "next/cache";

// export const metadata = {
//   title: "User page",
//   description: "Generated by create next app",
// };



//convert your dynamic routes into static


export async function generateStaticPrams() {
  const users = await GET();
  const IDs = users.map((user) => ({ id: user._id.toString() }));
  return IDs;
}

export const User = async () => {
  const res = await GET();

  const Users = await res.json();

  // const delUser = async (userId) => {
  //   // "use server"
  //   try {
  //     await userModel.findByIdAndDelete(userId);
  //     // await deleteUser(userId);
  //     // await DELETE(id);
  //     // await GET();
  //     revalidatePath("user");

  //     // router.reload();
  //   } catch (err) {
  //     console.error(err);
  //   }
  // };

  return (
    <>
      <div className="container">
        <div className="row">
          {Users.map((user) => (
            <div key={user._id} className="col-md-4 my-3 ">
              <div className="card">
                <div className="main-content">
                  <div className="header">
                    <span>Date :7-sep-2024</span>
                  </div>
                  <img
                    className="img-fluid img-thumbnail w-25 "
                    src="https://images.pexels.com/photos/39866/entrepreneur-startup-start-up-man-39866.jpeg?auto=compress&cs=tinysrgb&w=600"
                  />
                  <p className="heading ">Name :{user.userName}</p>
                  {/* <div className="categories my-1">
                    <span>Phone :{user.phone}</span>
                    
                  </div> */}
                  <div className="categories mb-5">
                    <span>Email :{user.email}</span>
                  </div>
                  <div className="categories my-1">
                    <span>
                      <Link href={`/user/${user._id}`} className="btn">
                        View Profile
                      </Link>
                    </span>
                  </div>
                </div>
                <form
                  action={async () => {
                    "use server";
                    await deleteUser(user._id);
                  }}
                >
                  <button className="btn btn-danger text-light"> Delete</button>
                </form>
                {/* <form
                  action={async () => {
                    "use server";
                    await deleteUser(user._id);
                  }}
                >
                  <button className="btn btn-danger text-light"> Delete</button>
                </form> */}
              </div>
            </div>
          ))}
        </div>
      </div>
    </>
  );
};
export default User;
