import React from 'react'
export const metadata = {
  title:"Contact US  page ",
  description: "Generated by create next app",
};
export default function ContactUS() {
  return (

<>
<div className="container mt-5">
      <div className="row">
        <div className="col-md-12">
          <h1 className="display-4 text-primary">Contact Us</h1>
          <p className="lead text-secondary">
            If you have any questions or need further information, please feel free to contact us.
          </p>
          <hr className="my-4" />
          <form>
            <div className="form-group">
              <label htmlFor="name">Name</label>
              <input type="text" className="form-control" id="name" placeholder="Enter your name" />
            </div>
            <div className="form-group">
              <label htmlFor="email">Email address</label>
              <input type="email" className="form-control" id="email" placeholder="Enter your email" />
            </div>
            <div className="form-group">
              <label htmlFor="message">Message</label>
              <textarea className="form-control" id="message" rows="3" placeholder="Enter your message"></textarea>
            </div>
            <button type="submit" className="btn btn-primary">Submit</button>
          </form>
        </div>
      </div>
    </div>
</>  )
}
